### ISSUE TITLE
R versions >4.4.0 not in sysdata

### ISSUE THREAD

**Issue by brancengregory** [ropensci/rix#360]
Howdy,

I dropped by to give the `renv2nix` function a try and on first run got this error:

> Error in rix(r_ver = "4.4.2", r_pkgs = "renv", git_pkgs = NULL) : 
> argument "project_path" is missing, with no default

The `project_path` argument being necessary wasn't immediately clear. When added I then received:

> Error in get_latest(r_ver) : The provided R version is likely wrong.
> Please check that you provided a correct R version.
> You can list available versions using `available_r()`.
> You can also directly provide a commit, but you need to make sure it points to the right repo used by `rix()`.

Listing versions as recommended I noticed the highest version is `4.4.0`. The underlying `sysdata` table doesn't include higher versions.

**Comment by brancengregory** [comment]
I see how that is being populated and logged in `data-raw/DATASET.R` but I'm unsure where those values are coming from so I can't make a PR

**Comment by b-rodrigues** [comment]
To get the latest version, you should use the keyword "latest", but for now, this is at version 4.4.1. Version 4.4.2 is not yet in nixpkgs because there is a new NixOS release coming, and the builders were 100% focused on building the more critical packages, and the R tree had to wait. 

We should be able to get some capacity soon to start building the packages. We don’t want to include a new R version without being able to build all CRAN and Bioconductor packages beforehand to check that everything works well.

The way this is done now will change though, I agree that this is not ideal. I will make clearer error messages.

**Comment by b-rodrigues** [comment]
P.S.: you can learn more about the release schedule here https://docs.ropensci.org/rix/articles/z-bleeding_edge.html

**Comment by b-rodrigues** [comment]
oops, this was not supposed to be closed

**Comment by b-rodrigues** [comment]
In the latest dev version, `renv2nix()` now includes a new `override_r_ver` argument that allows you to manually specify the R version that should be included in the default.nix file. This doesn’t entirely solve the issue here, but you can now use a version that is included by specifying, for example, `override_r_ver = "4.4.0"` in the call to `renv2nix()`.
